### ISSUE TITLE
Feature: User can view all the operators

### ISSUE THREAD

**Issue by t-doan** [t-doan/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all the operators and all their information from the API.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user load the page or clicks on the "operators" link, it will load all the operators in the API. When the user clicks on an image of an operator, it will pop a modal that shows the operator's information such as their name, bio, lore, and image(s). 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://github.com/t-doan/ajax-project/assets/26643555/fe728d12-4de7-4670-8b1f-e7be18a83c63)
![image](https://github.com/t-doan/ajax-project/assets/26643555/d5bd507f-c888-4c85-ab58-89ae6d71aa0e)
![image](https://github.com/t-doan/ajax-project/assets/26643555/806c5c31-47fe-4a26-b468-2c36410865e7)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create the HTML layout to match the figma
- [x] Create HTML layout for modal
- [x] Add an event listener that listen to whenever an operator is clicked, a modal pops up with their information
- [x] Access the API and request the information needed
- [ ] Create an object to store and pass to a function to load operators
- [ ] Add `beforeloaded` to store information into localStorage
- [x] Create an event listener on the `classes` that will filter out the operators that matches to the `classes` selected
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
